-- Slice 2 of celina 2: transactions ledger, payment recipients, cards,
-- and the OvlascenoLice (authorized person) entity for poslovni cards.
--
-- "Payments" and "transfers" are not separate tables — they are
-- conceptual UX-level operations that compose 1..N rows of the
-- transactions table sharing an op_id. This collapses the schema and
-- makes the "Pregled plaćanja" UI a single-table query.

-- =====================================================================
-- transactions: every account-level money movement
-- =====================================================================
--
-- One row per leg. A same-currency intra-bank payment = 1 row. A
-- menjačnica path between two same-bank accounts in different
-- currencies = 3 rows sharing op_id (debit source → bank's source-
-- currency house, bank's source-currency house → bank's dest-currency
-- house at the day's rate, bank's dest-currency house → destination).
--
-- recipient_name / payment_code / purpose / reference_number sit on the
-- *first* leg of an op_kind='payment' op (we don't denormalize them
-- across every leg). Other op kinds leave them null.
create table "bank".transactions (
    id                  uuid primary key default gen_random_uuid(),
    -- Groups all legs of the same UX-level operation. Generated by
    -- the bank service (a fresh UUID per payment/transfer/exchange).
    op_id               uuid not null,
    op_kind             text not null check (op_kind in ('payment','transfer','exchange','fee')),
    leg_index           int  not null default 1, -- 1-based leg ordering inside an op

    from_account_id     uuid not null references "bank".accounts(id) on delete restrict,
    to_account_id       uuid not null references "bank".accounts(id) on delete restrict,
    from_amount         numeric(20,4) not null check (from_amount > 0),
    to_amount           numeric(20,4) not null check (to_amount   > 0),
    rate                numeric(20,8), -- null when from/to are same currency

    -- Payment metadata. Lives on the first leg only.
    recipient_name      text,
    payment_code        text,
    reference_number    text,
    purpose             text,
    initiator_client_id uuid,

    status              text not null default 'realized' check (status in ('realized','rejected','processing')),
    created_at          timestamptz not null default now()
);

create index transactions_op_idx        on "bank".transactions (op_id);
create index transactions_from_idx      on "bank".transactions (from_account_id);
create index transactions_to_idx        on "bank".transactions (to_account_id);
create index transactions_initiator_idx on "bank".transactions (initiator_client_id);
create index transactions_kind_idx      on "bank".transactions (op_kind);
create index transactions_created_idx   on "bank".transactions (created_at desc);

-- =====================================================================
-- payment_recipients: saved templates ("Primaoci plaćanja")
-- =====================================================================
create table "bank".payment_recipients (
    id              uuid primary key default gen_random_uuid(),
    -- The client who saved this template. Cross-schema FK forbidden by
    -- convention, but the column is required so we can scope
    -- list/delete by owner without a join.
    client_id       uuid not null,
    name            text not null,
    account_number  text not null check (length(account_number) = 18),
    created_at      timestamptz not null default now(),
    unique (client_id, account_number)
);

create index payment_recipients_client_idx on "bank".payment_recipients (client_id);

-- =====================================================================
-- authorized_persons (OvlascenoLice)
-- =====================================================================
--
-- Per spec p.29: OvlascenoLice exists for tracking only — they don't
-- log into the app. Used to attribute a card on a Poslovni account to
-- a specific person other than the company owner.
create table "bank".authorized_persons (
    id            uuid primary key default gen_random_uuid(),
    first_name    text not null,
    last_name     text not null,
    date_of_birth date not null,
    gender        text not null check (gender in ('male','female','other')),
    email         text not null,
    phone         text not null,
    address       text not null,
    company_id    uuid not null references "bank".companies(id) on delete cascade,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

create index authorized_persons_company_idx on "bank".authorized_persons (company_id);

-- =====================================================================
-- cards
-- =====================================================================
--
-- Card numbers are stored in clear (they're not secrets — they're on
-- the physical card). CVV is hashed at rest; we use the same argon2id
-- machinery as passwords, scoped to a separate column so we never
-- accidentally compare against a password hash.
--
-- expires_at is set by the bank service: 4 years from creation per
-- typical industry default (spec p.28 leaves it open).
--
-- Card limits (per spec p.27):
--   * Lični račun: max 2 cards per account
--   * Poslovni račun: max 1 card per OvlascenoLice or per the company owner
-- These are enforced in the service layer (queries are simpler there
-- than in a check constraint that would need a window over the table).
create table "bank".cards (
    id                   uuid primary key default gen_random_uuid(),
    number               text not null unique,
    cvv_hash             text not null,
    brand                text not null check (brand in ('visa','mastercard','dinacard','amex')),
    name                 text not null, -- e.g. "Debit"
    account_id           uuid not null references "bank".accounts(id) on delete restrict,
    -- Set to a person on a poslovni account; null when the card belongs
    -- to a personal account (or to the company's owner — owner cards
    -- store the company link via account → company).
    authorized_person_id uuid references "bank".authorized_persons(id) on delete set null,
    card_limit           numeric(20,4) not null default 0,
    expires_at           timestamptz not null,
    status               text not null default 'active' check (status in ('active','blocked','deactivated')),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

create index cards_account_idx          on "bank".cards (account_id);
create index cards_authorized_idx       on "bank".cards (authorized_person_id);
create index cards_status_idx           on "bank".cards (status);
